name: flutter_contentful
version: "0.1.0"
description: Contentful Delivery API client for Dart. This Dart package is a small abstraction on top of the Contentful Delivery API.
homepage: https://github.com/bennibau/flutter_contentful
repository: https://github.com/bennibau/flutter_contentful

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  equatable: ^1.0.0
  http: ^0.12.0
  json_annotation: ^3.0.0
  meta: ^1.1.6

dev_dependencies:
  build_runner: ^1.0.0
  collection: ^1.14.12
  json_serializable: ^3.2.0
  test: ^1.9.4
